//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MellatBankPaymentService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://interfaces.core.sw.bps.com/", ConfigurationName="MellatBankPaymentService.IPaymentGateway")]
    internal interface IPaymentGateway
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MellatBankPaymentService.bpRefundRequestResponse> bpRefundRequestAsync(MellatBankPaymentService.bpRefundRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MellatBankPaymentService.bpSaleReferenceIdRequestResponse> bpSaleReferenceIdRequestAsync(MellatBankPaymentService.bpSaleReferenceIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MellatBankPaymentService.bpDynamicPayRequestResponse> bpDynamicPayRequestAsync(MellatBankPaymentService.bpDynamicPayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MellatBankPaymentService.bpInquiryRequestResponse> bpInquiryRequestAsync(MellatBankPaymentService.bpInquiryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MellatBankPaymentService.bpSettleRequestResponse> bpSettleRequestAsync(MellatBankPaymentService.bpSettleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MellatBankPaymentService.bpChargePayRequestResponse> bpChargePayRequestAsync(MellatBankPaymentService.bpChargePayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MellatBankPaymentService.bpCumulativeDynamicPayRequestResponse> bpCumulativeDynamicPayRequestAsync(MellatBankPaymentService.bpCumulativeDynamicPayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MellatBankPaymentService.bpPayRequestResponse> bpPayRequestAsync(MellatBankPaymentService.bpPayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MellatBankPaymentService.bpRefundInquiryRequestResponse> bpRefundInquiryRequestAsync(MellatBankPaymentService.bpRefundInquiryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MellatBankPaymentService.bpReversalRequestResponse> bpReversalRequestAsync(MellatBankPaymentService.bpReversalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MellatBankPaymentService.bpPosRefundRequestResponse> bpPosRefundRequestAsync(MellatBankPaymentService.bpPosRefundRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MellatBankPaymentService.bpRefundToPANRequestResponse> bpRefundToPANRequestAsync(MellatBankPaymentService.bpRefundToPANRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MellatBankPaymentService.bpVerifyRequestResponse> bpVerifyRequestAsync(MellatBankPaymentService.bpVerifyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MellatBankPaymentService.bpRefundVerifyRequestResponse> bpRefundVerifyRequestAsync(MellatBankPaymentService.bpRefundVerifyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bpRefundRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpRefundRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public MellatBankPaymentService.bpRefundRequestBody Body;
        
        public bpRefundRequest()
        {
        }
        
        public bpRefundRequest(MellatBankPaymentService.bpRefundRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class bpRefundRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long saleOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long saleReferenceId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public long refundAmount;
        
        public bpRefundRequestBody()
        {
        }
        
        public bpRefundRequestBody(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId, long refundAmount)
        {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.saleOrderId = saleOrderId;
            this.saleReferenceId = saleReferenceId;
            this.refundAmount = refundAmount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bpRefundRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpRefundRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public MellatBankPaymentService.bpRefundRequestResponseBody Body;
        
        public bpRefundRequestResponse()
        {
        }
        
        public bpRefundRequestResponse(MellatBankPaymentService.bpRefundRequestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class bpRefundRequestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpRefundRequestResponseBody()
        {
        }
        
        public bpRefundRequestResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bpSaleReferenceIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpSaleReferenceIdRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public MellatBankPaymentService.bpSaleReferenceIdRequestBody Body;
        
        public bpSaleReferenceIdRequest()
        {
        }
        
        public bpSaleReferenceIdRequest(MellatBankPaymentService.bpSaleReferenceIdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class bpSaleReferenceIdRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long saleOrderId;
        
        public bpSaleReferenceIdRequestBody()
        {
        }
        
        public bpSaleReferenceIdRequestBody(long terminalId, string userName, string userPassword, long orderId, long saleOrderId)
        {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.saleOrderId = saleOrderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bpSaleReferenceIdRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpSaleReferenceIdRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public MellatBankPaymentService.bpSaleReferenceIdRequestResponseBody Body;
        
        public bpSaleReferenceIdRequestResponse()
        {
        }
        
        public bpSaleReferenceIdRequestResponse(MellatBankPaymentService.bpSaleReferenceIdRequestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class bpSaleReferenceIdRequestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpSaleReferenceIdRequestResponseBody()
        {
        }
        
        public bpSaleReferenceIdRequestResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bpDynamicPayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpDynamicPayRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public MellatBankPaymentService.bpDynamicPayRequestBody Body;
        
        public bpDynamicPayRequest()
        {
        }
        
        public bpDynamicPayRequest(MellatBankPaymentService.bpDynamicPayRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class bpDynamicPayRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string localDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string localTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string additionalData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string callBackUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string payerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public long subServiceId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string mobileNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string encPan;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string panHiddenMode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string cartItem;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string enc;
        
        public bpDynamicPayRequestBody()
        {
        }
        
        public bpDynamicPayRequestBody(
                    long terminalId, 
                    string userName, 
                    string userPassword, 
                    long orderId, 
                    long amount, 
                    string localDate, 
                    string localTime, 
                    string additionalData, 
                    string callBackUrl, 
                    string payerId, 
                    long subServiceId, 
                    string mobileNo, 
                    string encPan, 
                    string panHiddenMode, 
                    string cartItem, 
                    string enc)
        {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.amount = amount;
            this.localDate = localDate;
            this.localTime = localTime;
            this.additionalData = additionalData;
            this.callBackUrl = callBackUrl;
            this.payerId = payerId;
            this.subServiceId = subServiceId;
            this.mobileNo = mobileNo;
            this.encPan = encPan;
            this.panHiddenMode = panHiddenMode;
            this.cartItem = cartItem;
            this.enc = enc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bpDynamicPayRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpDynamicPayRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public MellatBankPaymentService.bpDynamicPayRequestResponseBody Body;
        
        public bpDynamicPayRequestResponse()
        {
        }
        
        public bpDynamicPayRequestResponse(MellatBankPaymentService.bpDynamicPayRequestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class bpDynamicPayRequestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpDynamicPayRequestResponseBody()
        {
        }
        
        public bpDynamicPayRequestResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bpInquiryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpInquiryRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public MellatBankPaymentService.bpInquiryRequestBody Body;
        
        public bpInquiryRequest()
        {
        }
        
        public bpInquiryRequest(MellatBankPaymentService.bpInquiryRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class bpInquiryRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long saleOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long saleReferenceId;
        
        public bpInquiryRequestBody()
        {
        }
        
        public bpInquiryRequestBody(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId)
        {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.saleOrderId = saleOrderId;
            this.saleReferenceId = saleReferenceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bpInquiryRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpInquiryRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public MellatBankPaymentService.bpInquiryRequestResponseBody Body;
        
        public bpInquiryRequestResponse()
        {
        }
        
        public bpInquiryRequestResponse(MellatBankPaymentService.bpInquiryRequestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class bpInquiryRequestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpInquiryRequestResponseBody()
        {
        }
        
        public bpInquiryRequestResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bpSettleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpSettleRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public MellatBankPaymentService.bpSettleRequestBody Body;
        
        public bpSettleRequest()
        {
        }
        
        public bpSettleRequest(MellatBankPaymentService.bpSettleRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class bpSettleRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long saleOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long saleReferenceId;
        
        public bpSettleRequestBody()
        {
        }
        
        public bpSettleRequestBody(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId)
        {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.saleOrderId = saleOrderId;
            this.saleReferenceId = saleReferenceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bpSettleRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpSettleRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public MellatBankPaymentService.bpSettleRequestResponseBody Body;
        
        public bpSettleRequestResponse()
        {
        }
        
        public bpSettleRequestResponse(MellatBankPaymentService.bpSettleRequestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class bpSettleRequestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpSettleRequestResponseBody()
        {
        }
        
        public bpSettleRequestResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bpChargePayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpChargePayRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public MellatBankPaymentService.bpChargePayRequestBody Body;
        
        public bpChargePayRequest()
        {
        }
        
        public bpChargePayRequest(MellatBankPaymentService.bpChargePayRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class bpChargePayRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string localDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string localTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string additionalData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string callBackUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string payerId;
        
        public bpChargePayRequestBody()
        {
        }
        
        public bpChargePayRequestBody(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, string payerId)
        {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.amount = amount;
            this.localDate = localDate;
            this.localTime = localTime;
            this.additionalData = additionalData;
            this.callBackUrl = callBackUrl;
            this.payerId = payerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bpChargePayRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpChargePayRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public MellatBankPaymentService.bpChargePayRequestResponseBody Body;
        
        public bpChargePayRequestResponse()
        {
        }
        
        public bpChargePayRequestResponse(MellatBankPaymentService.bpChargePayRequestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class bpChargePayRequestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpChargePayRequestResponseBody()
        {
        }
        
        public bpChargePayRequestResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bpCumulativeDynamicPayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpCumulativeDynamicPayRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public MellatBankPaymentService.bpCumulativeDynamicPayRequestBody Body;
        
        public bpCumulativeDynamicPayRequest()
        {
        }
        
        public bpCumulativeDynamicPayRequest(MellatBankPaymentService.bpCumulativeDynamicPayRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class bpCumulativeDynamicPayRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string localDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string localTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string additionalData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string callBackUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string mobileNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string encPan;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string panHiddenMode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string cartItem;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string enc;
        
        public bpCumulativeDynamicPayRequestBody()
        {
        }
        
        public bpCumulativeDynamicPayRequestBody(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, string mobileNo, string encPan, string panHiddenMode, string cartItem, string enc)
        {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.amount = amount;
            this.localDate = localDate;
            this.localTime = localTime;
            this.additionalData = additionalData;
            this.callBackUrl = callBackUrl;
            this.mobileNo = mobileNo;
            this.encPan = encPan;
            this.panHiddenMode = panHiddenMode;
            this.cartItem = cartItem;
            this.enc = enc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bpCumulativeDynamicPayRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpCumulativeDynamicPayRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public MellatBankPaymentService.bpCumulativeDynamicPayRequestResponseBody Body;
        
        public bpCumulativeDynamicPayRequestResponse()
        {
        }
        
        public bpCumulativeDynamicPayRequestResponse(MellatBankPaymentService.bpCumulativeDynamicPayRequestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class bpCumulativeDynamicPayRequestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpCumulativeDynamicPayRequestResponseBody()
        {
        }
        
        public bpCumulativeDynamicPayRequestResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bpPayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpPayRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public MellatBankPaymentService.bpPayRequestBody Body;
        
        public bpPayRequest()
        {
        }
        
        public bpPayRequest(MellatBankPaymentService.bpPayRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class bpPayRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string localDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string localTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string additionalData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string callBackUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string payerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string mobileNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string encPan;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string panHiddenMode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string cartItem;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string enc;
        
        public bpPayRequestBody()
        {
        }
        
        public bpPayRequestBody(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, string payerId, string mobileNo, string encPan, string panHiddenMode, string cartItem, string enc)
        {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.amount = amount;
            this.localDate = localDate;
            this.localTime = localTime;
            this.additionalData = additionalData;
            this.callBackUrl = callBackUrl;
            this.payerId = payerId;
            this.mobileNo = mobileNo;
            this.encPan = encPan;
            this.panHiddenMode = panHiddenMode;
            this.cartItem = cartItem;
            this.enc = enc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bpPayRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpPayRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public MellatBankPaymentService.bpPayRequestResponseBody Body;
        
        public bpPayRequestResponse()
        {
        }
        
        public bpPayRequestResponse(MellatBankPaymentService.bpPayRequestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class bpPayRequestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpPayRequestResponseBody()
        {
        }
        
        public bpPayRequestResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bpRefundInquiryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpRefundInquiryRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public MellatBankPaymentService.bpRefundInquiryRequestBody Body;
        
        public bpRefundInquiryRequest()
        {
        }
        
        public bpRefundInquiryRequest(MellatBankPaymentService.bpRefundInquiryRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class bpRefundInquiryRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long refundOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long refundReferenceId;
        
        public bpRefundInquiryRequestBody()
        {
        }
        
        public bpRefundInquiryRequestBody(long terminalId, string userName, string userPassword, long orderId, long refundOrderId, long refundReferenceId)
        {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.refundOrderId = refundOrderId;
            this.refundReferenceId = refundReferenceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bpRefundInquiryRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpRefundInquiryRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public MellatBankPaymentService.bpRefundInquiryRequestResponseBody Body;
        
        public bpRefundInquiryRequestResponse()
        {
        }
        
        public bpRefundInquiryRequestResponse(MellatBankPaymentService.bpRefundInquiryRequestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class bpRefundInquiryRequestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpRefundInquiryRequestResponseBody()
        {
        }
        
        public bpRefundInquiryRequestResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bpReversalRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpReversalRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public MellatBankPaymentService.bpReversalRequestBody Body;
        
        public bpReversalRequest()
        {
        }
        
        public bpReversalRequest(MellatBankPaymentService.bpReversalRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class bpReversalRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long saleOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long saleReferenceId;
        
        public bpReversalRequestBody()
        {
        }
        
        public bpReversalRequestBody(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId)
        {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.saleOrderId = saleOrderId;
            this.saleReferenceId = saleReferenceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bpReversalRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpReversalRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public MellatBankPaymentService.bpReversalRequestResponseBody Body;
        
        public bpReversalRequestResponse()
        {
        }
        
        public bpReversalRequestResponse(MellatBankPaymentService.bpReversalRequestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class bpReversalRequestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpReversalRequestResponseBody()
        {
        }
        
        public bpReversalRequestResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bpPosRefundRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpPosRefundRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public MellatBankPaymentService.bpPosRefundRequestBody Body;
        
        public bpPosRefundRequest()
        {
        }
        
        public bpPosRefundRequest(MellatBankPaymentService.bpPosRefundRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class bpPosRefundRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long saleReferenceId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long refundAmount;
        
        public bpPosRefundRequestBody()
        {
        }
        
        public bpPosRefundRequestBody(string user, string password, long saleReferenceId, long refundAmount)
        {
            this.user = user;
            this.password = password;
            this.saleReferenceId = saleReferenceId;
            this.refundAmount = refundAmount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bpPosRefundRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpPosRefundRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public MellatBankPaymentService.bpPosRefundRequestResponseBody Body;
        
        public bpPosRefundRequestResponse()
        {
        }
        
        public bpPosRefundRequestResponse(MellatBankPaymentService.bpPosRefundRequestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class bpPosRefundRequestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpPosRefundRequestResponseBody()
        {
        }
        
        public bpPosRefundRequestResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bpRefundToPANRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpRefundToPANRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public MellatBankPaymentService.bpRefundToPANRequestBody Body;
        
        public bpRefundToPANRequest()
        {
        }
        
        public bpRefundToPANRequest(MellatBankPaymentService.bpRefundToPANRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class bpRefundToPANRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long pan;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long saleReferenceId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string mobileNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string orderId;
        
        public bpRefundToPANRequestBody()
        {
        }
        
        public bpRefundToPANRequestBody(string user, string password, long pan, long amount, long saleReferenceId, long terminalId, string mobileNo, string orderId)
        {
            this.user = user;
            this.password = password;
            this.pan = pan;
            this.amount = amount;
            this.saleReferenceId = saleReferenceId;
            this.terminalId = terminalId;
            this.mobileNo = mobileNo;
            this.orderId = orderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bpRefundToPANRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpRefundToPANRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public MellatBankPaymentService.bpRefundToPANRequestResponseBody Body;
        
        public bpRefundToPANRequestResponse()
        {
        }
        
        public bpRefundToPANRequestResponse(MellatBankPaymentService.bpRefundToPANRequestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class bpRefundToPANRequestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpRefundToPANRequestResponseBody()
        {
        }
        
        public bpRefundToPANRequestResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bpVerifyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpVerifyRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public MellatBankPaymentService.bpVerifyRequestBody Body;
        
        public bpVerifyRequest()
        {
        }
        
        public bpVerifyRequest(MellatBankPaymentService.bpVerifyRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class bpVerifyRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long saleOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long saleReferenceId;
        
        public bpVerifyRequestBody()
        {
        }
        
        public bpVerifyRequestBody(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId)
        {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.saleOrderId = saleOrderId;
            this.saleReferenceId = saleReferenceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bpVerifyRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpVerifyRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public MellatBankPaymentService.bpVerifyRequestResponseBody Body;
        
        public bpVerifyRequestResponse()
        {
        }
        
        public bpVerifyRequestResponse(MellatBankPaymentService.bpVerifyRequestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class bpVerifyRequestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpVerifyRequestResponseBody()
        {
        }
        
        public bpVerifyRequestResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bpRefundVerifyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpRefundVerifyRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public MellatBankPaymentService.bpRefundVerifyRequestBody Body;
        
        public bpRefundVerifyRequest()
        {
        }
        
        public bpRefundVerifyRequest(MellatBankPaymentService.bpRefundVerifyRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class bpRefundVerifyRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long refundOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long refundReferenceId;
        
        public bpRefundVerifyRequestBody()
        {
        }
        
        public bpRefundVerifyRequestBody(long terminalId, string userName, string userPassword, long orderId, long refundOrderId, long refundReferenceId)
        {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.refundOrderId = refundOrderId;
            this.refundReferenceId = refundReferenceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class bpRefundVerifyRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpRefundVerifyRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public MellatBankPaymentService.bpRefundVerifyRequestResponseBody Body;
        
        public bpRefundVerifyRequestResponse()
        {
        }
        
        public bpRefundVerifyRequestResponse(MellatBankPaymentService.bpRefundVerifyRequestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    internal partial class bpRefundVerifyRequestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpRefundVerifyRequestResponseBody()
        {
        }
        
        public bpRefundVerifyRequestResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    internal interface IPaymentGatewayChannel : MellatBankPaymentService.IPaymentGateway, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    internal partial class PaymentGatewayClient : System.ServiceModel.ClientBase<MellatBankPaymentService.IPaymentGateway>, MellatBankPaymentService.IPaymentGateway
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PaymentGatewayClient() : 
                base(PaymentGatewayClient.GetDefaultBinding(), PaymentGatewayClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.PaymentGatewayImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaymentGatewayClient(EndpointConfiguration endpointConfiguration) : 
                base(PaymentGatewayClient.GetBindingForEndpoint(endpointConfiguration), PaymentGatewayClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaymentGatewayClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PaymentGatewayClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaymentGatewayClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PaymentGatewayClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaymentGatewayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MellatBankPaymentService.bpRefundRequestResponse> MellatBankPaymentService.IPaymentGateway.bpRefundRequestAsync(MellatBankPaymentService.bpRefundRequest request)
        {
            return base.Channel.bpRefundRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<MellatBankPaymentService.bpRefundRequestResponse> bpRefundRequestAsync(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId, long refundAmount)
        {
            MellatBankPaymentService.bpRefundRequest inValue = new MellatBankPaymentService.bpRefundRequest();
            inValue.Body = new MellatBankPaymentService.bpRefundRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            inValue.Body.refundAmount = refundAmount;
            return ((MellatBankPaymentService.IPaymentGateway)(this)).bpRefundRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MellatBankPaymentService.bpSaleReferenceIdRequestResponse> MellatBankPaymentService.IPaymentGateway.bpSaleReferenceIdRequestAsync(MellatBankPaymentService.bpSaleReferenceIdRequest request)
        {
            return base.Channel.bpSaleReferenceIdRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<MellatBankPaymentService.bpSaleReferenceIdRequestResponse> bpSaleReferenceIdRequestAsync(long terminalId, string userName, string userPassword, long orderId, long saleOrderId)
        {
            MellatBankPaymentService.bpSaleReferenceIdRequest inValue = new MellatBankPaymentService.bpSaleReferenceIdRequest();
            inValue.Body = new MellatBankPaymentService.bpSaleReferenceIdRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            return ((MellatBankPaymentService.IPaymentGateway)(this)).bpSaleReferenceIdRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MellatBankPaymentService.bpDynamicPayRequestResponse> MellatBankPaymentService.IPaymentGateway.bpDynamicPayRequestAsync(MellatBankPaymentService.bpDynamicPayRequest request)
        {
            return base.Channel.bpDynamicPayRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<MellatBankPaymentService.bpDynamicPayRequestResponse> bpDynamicPayRequestAsync(
                    long terminalId, 
                    string userName, 
                    string userPassword, 
                    long orderId, 
                    long amount, 
                    string localDate, 
                    string localTime, 
                    string additionalData, 
                    string callBackUrl, 
                    string payerId, 
                    long subServiceId, 
                    string mobileNo, 
                    string encPan, 
                    string panHiddenMode, 
                    string cartItem, 
                    string enc)
        {
            MellatBankPaymentService.bpDynamicPayRequest inValue = new MellatBankPaymentService.bpDynamicPayRequest();
            inValue.Body = new MellatBankPaymentService.bpDynamicPayRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.amount = amount;
            inValue.Body.localDate = localDate;
            inValue.Body.localTime = localTime;
            inValue.Body.additionalData = additionalData;
            inValue.Body.callBackUrl = callBackUrl;
            inValue.Body.payerId = payerId;
            inValue.Body.subServiceId = subServiceId;
            inValue.Body.mobileNo = mobileNo;
            inValue.Body.encPan = encPan;
            inValue.Body.panHiddenMode = panHiddenMode;
            inValue.Body.cartItem = cartItem;
            inValue.Body.enc = enc;
            return ((MellatBankPaymentService.IPaymentGateway)(this)).bpDynamicPayRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MellatBankPaymentService.bpInquiryRequestResponse> MellatBankPaymentService.IPaymentGateway.bpInquiryRequestAsync(MellatBankPaymentService.bpInquiryRequest request)
        {
            return base.Channel.bpInquiryRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<MellatBankPaymentService.bpInquiryRequestResponse> bpInquiryRequestAsync(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId)
        {
            MellatBankPaymentService.bpInquiryRequest inValue = new MellatBankPaymentService.bpInquiryRequest();
            inValue.Body = new MellatBankPaymentService.bpInquiryRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            return ((MellatBankPaymentService.IPaymentGateway)(this)).bpInquiryRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MellatBankPaymentService.bpSettleRequestResponse> MellatBankPaymentService.IPaymentGateway.bpSettleRequestAsync(MellatBankPaymentService.bpSettleRequest request)
        {
            return base.Channel.bpSettleRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<MellatBankPaymentService.bpSettleRequestResponse> bpSettleRequestAsync(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId)
        {
            MellatBankPaymentService.bpSettleRequest inValue = new MellatBankPaymentService.bpSettleRequest();
            inValue.Body = new MellatBankPaymentService.bpSettleRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            return ((MellatBankPaymentService.IPaymentGateway)(this)).bpSettleRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MellatBankPaymentService.bpChargePayRequestResponse> MellatBankPaymentService.IPaymentGateway.bpChargePayRequestAsync(MellatBankPaymentService.bpChargePayRequest request)
        {
            return base.Channel.bpChargePayRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<MellatBankPaymentService.bpChargePayRequestResponse> bpChargePayRequestAsync(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, string payerId)
        {
            MellatBankPaymentService.bpChargePayRequest inValue = new MellatBankPaymentService.bpChargePayRequest();
            inValue.Body = new MellatBankPaymentService.bpChargePayRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.amount = amount;
            inValue.Body.localDate = localDate;
            inValue.Body.localTime = localTime;
            inValue.Body.additionalData = additionalData;
            inValue.Body.callBackUrl = callBackUrl;
            inValue.Body.payerId = payerId;
            return ((MellatBankPaymentService.IPaymentGateway)(this)).bpChargePayRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MellatBankPaymentService.bpCumulativeDynamicPayRequestResponse> MellatBankPaymentService.IPaymentGateway.bpCumulativeDynamicPayRequestAsync(MellatBankPaymentService.bpCumulativeDynamicPayRequest request)
        {
            return base.Channel.bpCumulativeDynamicPayRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<MellatBankPaymentService.bpCumulativeDynamicPayRequestResponse> bpCumulativeDynamicPayRequestAsync(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, string mobileNo, string encPan, string panHiddenMode, string cartItem, string enc)
        {
            MellatBankPaymentService.bpCumulativeDynamicPayRequest inValue = new MellatBankPaymentService.bpCumulativeDynamicPayRequest();
            inValue.Body = new MellatBankPaymentService.bpCumulativeDynamicPayRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.amount = amount;
            inValue.Body.localDate = localDate;
            inValue.Body.localTime = localTime;
            inValue.Body.additionalData = additionalData;
            inValue.Body.callBackUrl = callBackUrl;
            inValue.Body.mobileNo = mobileNo;
            inValue.Body.encPan = encPan;
            inValue.Body.panHiddenMode = panHiddenMode;
            inValue.Body.cartItem = cartItem;
            inValue.Body.enc = enc;
            return ((MellatBankPaymentService.IPaymentGateway)(this)).bpCumulativeDynamicPayRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MellatBankPaymentService.bpPayRequestResponse> MellatBankPaymentService.IPaymentGateway.bpPayRequestAsync(MellatBankPaymentService.bpPayRequest request)
        {
            return base.Channel.bpPayRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<MellatBankPaymentService.bpPayRequestResponse> bpPayRequestAsync(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, string payerId, string mobileNo, string encPan, string panHiddenMode, string cartItem, string enc)
        {
            MellatBankPaymentService.bpPayRequest inValue = new MellatBankPaymentService.bpPayRequest();
            inValue.Body = new MellatBankPaymentService.bpPayRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.amount = amount;
            inValue.Body.localDate = localDate;
            inValue.Body.localTime = localTime;
            inValue.Body.additionalData = additionalData;
            inValue.Body.callBackUrl = callBackUrl;
            inValue.Body.payerId = payerId;
            inValue.Body.mobileNo = mobileNo;
            inValue.Body.encPan = encPan;
            inValue.Body.panHiddenMode = panHiddenMode;
            inValue.Body.cartItem = cartItem;
            inValue.Body.enc = enc;
            return ((MellatBankPaymentService.IPaymentGateway)(this)).bpPayRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MellatBankPaymentService.bpRefundInquiryRequestResponse> MellatBankPaymentService.IPaymentGateway.bpRefundInquiryRequestAsync(MellatBankPaymentService.bpRefundInquiryRequest request)
        {
            return base.Channel.bpRefundInquiryRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<MellatBankPaymentService.bpRefundInquiryRequestResponse> bpRefundInquiryRequestAsync(long terminalId, string userName, string userPassword, long orderId, long refundOrderId, long refundReferenceId)
        {
            MellatBankPaymentService.bpRefundInquiryRequest inValue = new MellatBankPaymentService.bpRefundInquiryRequest();
            inValue.Body = new MellatBankPaymentService.bpRefundInquiryRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.refundOrderId = refundOrderId;
            inValue.Body.refundReferenceId = refundReferenceId;
            return ((MellatBankPaymentService.IPaymentGateway)(this)).bpRefundInquiryRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MellatBankPaymentService.bpReversalRequestResponse> MellatBankPaymentService.IPaymentGateway.bpReversalRequestAsync(MellatBankPaymentService.bpReversalRequest request)
        {
            return base.Channel.bpReversalRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<MellatBankPaymentService.bpReversalRequestResponse> bpReversalRequestAsync(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId)
        {
            MellatBankPaymentService.bpReversalRequest inValue = new MellatBankPaymentService.bpReversalRequest();
            inValue.Body = new MellatBankPaymentService.bpReversalRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            return ((MellatBankPaymentService.IPaymentGateway)(this)).bpReversalRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MellatBankPaymentService.bpPosRefundRequestResponse> MellatBankPaymentService.IPaymentGateway.bpPosRefundRequestAsync(MellatBankPaymentService.bpPosRefundRequest request)
        {
            return base.Channel.bpPosRefundRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<MellatBankPaymentService.bpPosRefundRequestResponse> bpPosRefundRequestAsync(string user, string password, long saleReferenceId, long refundAmount)
        {
            MellatBankPaymentService.bpPosRefundRequest inValue = new MellatBankPaymentService.bpPosRefundRequest();
            inValue.Body = new MellatBankPaymentService.bpPosRefundRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.saleReferenceId = saleReferenceId;
            inValue.Body.refundAmount = refundAmount;
            return ((MellatBankPaymentService.IPaymentGateway)(this)).bpPosRefundRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MellatBankPaymentService.bpRefundToPANRequestResponse> MellatBankPaymentService.IPaymentGateway.bpRefundToPANRequestAsync(MellatBankPaymentService.bpRefundToPANRequest request)
        {
            return base.Channel.bpRefundToPANRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<MellatBankPaymentService.bpRefundToPANRequestResponse> bpRefundToPANRequestAsync(string user, string password, long pan, long amount, long saleReferenceId, long terminalId, string mobileNo, string orderId)
        {
            MellatBankPaymentService.bpRefundToPANRequest inValue = new MellatBankPaymentService.bpRefundToPANRequest();
            inValue.Body = new MellatBankPaymentService.bpRefundToPANRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.pan = pan;
            inValue.Body.amount = amount;
            inValue.Body.saleReferenceId = saleReferenceId;
            inValue.Body.terminalId = terminalId;
            inValue.Body.mobileNo = mobileNo;
            inValue.Body.orderId = orderId;
            return ((MellatBankPaymentService.IPaymentGateway)(this)).bpRefundToPANRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MellatBankPaymentService.bpVerifyRequestResponse> MellatBankPaymentService.IPaymentGateway.bpVerifyRequestAsync(MellatBankPaymentService.bpVerifyRequest request)
        {
            return base.Channel.bpVerifyRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<MellatBankPaymentService.bpVerifyRequestResponse> bpVerifyRequestAsync(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId)
        {
            MellatBankPaymentService.bpVerifyRequest inValue = new MellatBankPaymentService.bpVerifyRequest();
            inValue.Body = new MellatBankPaymentService.bpVerifyRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            return ((MellatBankPaymentService.IPaymentGateway)(this)).bpVerifyRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MellatBankPaymentService.bpRefundVerifyRequestResponse> MellatBankPaymentService.IPaymentGateway.bpRefundVerifyRequestAsync(MellatBankPaymentService.bpRefundVerifyRequest request)
        {
            return base.Channel.bpRefundVerifyRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<MellatBankPaymentService.bpRefundVerifyRequestResponse> bpRefundVerifyRequestAsync(long terminalId, string userName, string userPassword, long orderId, long refundOrderId, long refundReferenceId)
        {
            MellatBankPaymentService.bpRefundVerifyRequest inValue = new MellatBankPaymentService.bpRefundVerifyRequest();
            inValue.Body = new MellatBankPaymentService.bpRefundVerifyRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.refundOrderId = refundOrderId;
            inValue.Body.refundReferenceId = refundReferenceId;
            return ((MellatBankPaymentService.IPaymentGateway)(this)).bpRefundVerifyRequestAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PaymentGatewayImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PaymentGatewayImplPort))
            {
                return new System.ServiceModel.EndpointAddress("https://bpm.shaparak.ir/pgwchannel/services/pgw");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PaymentGatewayClient.GetBindingForEndpoint(EndpointConfiguration.PaymentGatewayImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PaymentGatewayClient.GetEndpointAddress(EndpointConfiguration.PaymentGatewayImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            PaymentGatewayImplPort,
        }
    }
}
